### ISSUE TITLE
change default unit to mm instead of cm

### ISSUE THREAD

**Issue by shalaby7** [ansys/pyaedt-toolkits-antenna#284]
### 📝 Description of the feature

all antenna engineers and manufacturing techinians work with mm. creating models directly in mm instead of cm avoids one extra source of confusion or erros. and it takes the step of changing the unit away

### 💡 Steps for implementing the feature

in the code change teh default unit

**Comment by Samuelopez-ansys** [comment]
@shalaby7 Your suggestions have been applied.
